export const CIVIC_POINTS = {
  ALERT_SUBMITTED: 50,
  SIGHTING_VERIFIED: 500,
  POSTER_UPLOADED: 200,
  DIRECTORY_VERIFIED: 100,
  ALERT_SHARED: 25,
  ACTIVE_STANDBY: 10,
  WARDEN_THRESHOLD: 2000,
  BROADCAST_REDEMPTION_COST: 500,
} as const
