/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    media: Media;
    users: User;
    alerts: Alert;
    sightings: Sighting;
    'civic-point-ledger': CivicPointLedger;
    transactions: Transaction;
    'ocs-directory': OcsDirectory;
    'audit-logs': AuditLog;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    media: MediaSelect<false> | MediaSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    alerts: AlertsSelect<false> | AlertsSelect<true>;
    sightings: SightingsSelect<false> | SightingsSelect<true>;
    'civic-point-ledger': CivicPointLedgerSelect<false> | CivicPointLedgerSelect<true>;
    transactions: TransactionsSelect<false> | TransactionsSelect<true>;
    'ocs-directory': OcsDirectorySelect<false> | OcsDirectorySelect<true>;
    'audit-logs': AuditLogsSelect<false> | AuditLogsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt?: string | null;
  caption?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  name?: string | null;
  roles: ('user' | 'warden' | 'moderator' | 'editor' | 'super-admin')[];
  firebaseUID?: string | null;
  phoneNumber?: string | null;
  phoneVerified?: boolean | null;
  county?: string | null;
  subCounty?: string | null;
  ward?: string | null;
  /**
   * @minItems 2
   * @maxItems 2
   */
  location?: [number, number] | null;
  fcmTokens?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  civicPointsBalance?: number | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "alerts".
 */
export interface Alert {
  id: string;
  title: string;
  category: 'missing-person' | 'lost-vehicle' | 'lost-motorbike';
  obNumber: string;
  policeStation: string;
  socialMediaURL: string;
  socialMediaValid?: boolean | null;
  parityScore?: number | null;
  parityReasoning?: string | null;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  photo: string | Media;
  additionalPhotos?:
    | {
        photo?: (string | null) | Media;
        id?: string | null;
      }[]
    | null;
  /**
   * @minItems 2
   * @maxItems 2
   */
  lastSeenLocation?: [number, number] | null;
  lastSeenLocationName?: string | null;
  lastSeenDate?: string | null;
  alertRadius?: number | null;
  contactPhone?: string | null;
  submittedBy?: (string | null) | User;
  vehicleDetails?: {
    registrationNumber?: string | null;
    make?: string | null;
    model?: string | null;
    color?: string | null;
    yearOfManufacture?: number | null;
  };
  personDetails?: {
    fullName?: string | null;
    age?: number | null;
    gender?: ('male' | 'female' | 'other') | null;
    height?: string | null;
    clothingLastSeen?: string | null;
  };
  isPaidBroadcast?: boolean | null;
  broadcastTransaction?: (string | null) | Transaction;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "transactions".
 */
export interface Transaction {
  id: string;
  type: 'lost-property-broadcast' | 'radius-extension' | 'civic-points-redemption';
  amount: number;
  currency?: string | null;
  phoneNumber?: string | null;
  status?: ('pending' | 'completed' | 'failed') | null;
  reference: string;
  paystackTransactionId?: string | null;
  user?: (string | null) | User;
  alert?: (string | null) | Alert;
  metadata?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sightings".
 */
export interface Sighting {
  id: string;
  alert: string | Alert;
  reporter: string | User;
  /**
   * @minItems 2
   * @maxItems 2
   */
  location: [number, number];
  locationName?: string | null;
  sightingDate?: string | null;
  description: string;
  photo?: (string | null) | Media;
  verificationStatus?: ('pending' | 'verified' | 'rejected' | 'led-to-recovery') | null;
  verifiedBy?: (string | null) | User;
  verifiedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "civic-point-ledger".
 */
export interface CivicPointLedger {
  id: string;
  user: string | User;
  action:
    | 'alert-submitted'
    | 'sighting-verified'
    | 'poster-uploaded'
    | 'directory-verified'
    | 'alert-shared'
    | 'active-standby'
    | 'points-redeemed'
    | 'warden-promotion';
  points: number;
  description?: string | null;
  relatedAlert?: (string | null) | Alert;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ocs-directory".
 */
export interface OcsDirectory {
  id: string;
  stationName: string;
  ocsName?: string | null;
  phoneNumber: string;
  alternatePhone?: string | null;
  county: string;
  subCounty?: string | null;
  ward?: string | null;
  /**
   * @minItems 2
   * @maxItems 2
   */
  location?: [number, number] | null;
  lastVerified?: string | null;
  verifiedBy?: (string | null) | User;
  isActive?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audit-logs".
 */
export interface AuditLog {
  id: string;
  action: string;
  performedBy?: (string | null) | User;
  entity?: string | null;
  entityId?: string | null;
  details?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  ipAddress?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'alerts';
        value: string | Alert;
      } | null)
    | ({
        relationTo: 'sightings';
        value: string | Sighting;
      } | null)
    | ({
        relationTo: 'civic-point-ledger';
        value: string | CivicPointLedger;
      } | null)
    | ({
        relationTo: 'transactions';
        value: string | Transaction;
      } | null)
    | ({
        relationTo: 'ocs-directory';
        value: string | OcsDirectory;
      } | null)
    | ({
        relationTo: 'audit-logs';
        value: string | AuditLog;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  roles?: T;
  firebaseUID?: T;
  phoneNumber?: T;
  phoneVerified?: T;
  county?: T;
  subCounty?: T;
  ward?: T;
  location?: T;
  fcmTokens?: T;
  civicPointsBalance?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "alerts_select".
 */
export interface AlertsSelect<T extends boolean = true> {
  title?: T;
  category?: T;
  obNumber?: T;
  policeStation?: T;
  socialMediaURL?: T;
  socialMediaValid?: T;
  parityScore?: T;
  parityReasoning?: T;
  description?: T;
  photo?: T;
  additionalPhotos?:
    | T
    | {
        photo?: T;
        id?: T;
      };
  lastSeenLocation?: T;
  lastSeenLocationName?: T;
  lastSeenDate?: T;
  alertRadius?: T;
  contactPhone?: T;
  submittedBy?: T;
  vehicleDetails?:
    | T
    | {
        registrationNumber?: T;
        make?: T;
        model?: T;
        color?: T;
        yearOfManufacture?: T;
      };
  personDetails?:
    | T
    | {
        fullName?: T;
        age?: T;
        gender?: T;
        height?: T;
        clothingLastSeen?: T;
      };
  isPaidBroadcast?: T;
  broadcastTransaction?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sightings_select".
 */
export interface SightingsSelect<T extends boolean = true> {
  alert?: T;
  reporter?: T;
  location?: T;
  locationName?: T;
  sightingDate?: T;
  description?: T;
  photo?: T;
  verificationStatus?: T;
  verifiedBy?: T;
  verifiedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "civic-point-ledger_select".
 */
export interface CivicPointLedgerSelect<T extends boolean = true> {
  user?: T;
  action?: T;
  points?: T;
  description?: T;
  relatedAlert?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "transactions_select".
 */
export interface TransactionsSelect<T extends boolean = true> {
  type?: T;
  amount?: T;
  currency?: T;
  phoneNumber?: T;
  status?: T;
  reference?: T;
  paystackTransactionId?: T;
  user?: T;
  alert?: T;
  metadata?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ocs-directory_select".
 */
export interface OcsDirectorySelect<T extends boolean = true> {
  stationName?: T;
  ocsName?: T;
  phoneNumber?: T;
  alternatePhone?: T;
  county?: T;
  subCounty?: T;
  ward?: T;
  location?: T;
  lastVerified?: T;
  verifiedBy?: T;
  isActive?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audit-logs_select".
 */
export interface AuditLogsSelect<T extends boolean = true> {
  action?: T;
  performedBy?: T;
  entity?: T;
  entityId?: T;
  details?: T;
  ipAddress?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}